lane :bonjour do

UI.success "Bravo!"
UI.error "error"

scan(
	project: "fastLaneFrameworkUnitTest.xcodeproj",
	code_coverage: true
)

xcov

end

lane :deploy do

	version = get_version_number()
	print version

end
